[listener]
bind = "127.0.0.1:25577"
max_connections = 8196

[proxy]
compression_threshold = 256
max_players = 4000
online_mode = true
player_limit = -1
prevent_proxy_connections = false
motd = "§dAnother Lure proxy"
favicon = "server-icon.png"

[hosts]
"*" = "lobby"

[servers]
lobby = "127.0.0.1:25565"